# Generated by Django 3.0.8 on 2020-08-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.CharField(default='Active', max_length=12),
        ),
    ]
